<?xml version="1.0" ?>
<TestCase>
    <TcExpectedResult>PASS</TcExpectedResult>
    <Discription> 
&lt;div align=&quot;left&quot; style=&quot;min-height:9pt&quot;&gt;
&lt;font face=&quot;Arial&quot;&gt;&lt;span style=&quot;font-size:8pt&quot;&gt;Check the Warning screen for error EIO is presented for each sequential reboot&lt;/span&gt;&lt;/font&gt;
&lt;/div&gt;  
</Discription>
    <Domain>System_FastBoot</Domain>
    <Phase>CORE</Phase>
    <b2bContinuousMode>True</b2bContinuousMode>
    <Type>FUNCTIONAL</Type>
    <UseCase>PY_UNIT</UseCase>
    <b2bIteration>1</b2bIteration>
    <Parameters>
        <Parameter>
            <Name>HpalmName</Name>
            <Value>Display_IOError_after_system_datablock_O</Value>
        </Parameter>
        <Parameter>
            <Name>TEST_DATA_ROOT</Name>
            <Value>testplan/System_FastBoot</Value>
        </Parameter>
        <Parameter>
            <Name>TEST_CASE</Name>
            <Value>tests.System_FastBoot.P1-AOSP Verified Boot Reference Implementation (Verified Boot 2.0).Display_IOError_after_system_datablock_O</Value>
        </Parameter>
    </Parameters>
</TestCase>
